python/rascaline/status.py
Previously
```
Traceback (most recent call last):
File "rascaline/status.py", line 33, in _check_rascal_pointer
pointer.contents
ValueError: NULL pointer access
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "tmp.py", line 10, in <module>
cutoff_function={"ShiftedCosine": {"width": 0.5}},
File "rascaline/calculator.py", line 280, in __init__
super().__init__("spherical_expansion", parameters)
File "rascaline/calculator.py", line 111, in __init__
_check_rascal_pointer(self._as_parameter_)
File "rascaline/status.py", line 35, in _check_rascal_pointer
raise RascalError(last_error())
rascaline.status.RascalError: json error: unknown variant `GTO`, expected `Gto` at line 1 column 102
```
Now:
```
Traceback (most recent call last): …
```
=> Improve exception traceback when dealing with NULL pointers in Python

python/rascaline/_rascaline.py, python/rascaline/descriptor.py, python/tests/calculators.py, python/tests/descriptor.py, rascaline-c-api/rascaline.h, rascaline-c-api/src/descriptor.rs, rascaline-c-api/tests/c-api/calculator.cpp, rascaline-c-api/tests/c-api/descriptor.cpp, rascaline/benches/soap-power-spectrum.rs, rascaline/benches/spherical-expansion.rs, rascaline/src/calculator.rs, rascaline/src/calculators/dummy_calculator.rs, rascaline/src/calculators/mod.rs, rascaline/src/calculators/soap/power_spectrum.rs, rascaline/src/calculators/soap/spherical_expansion.rs, rascaline/src/calculators/sorted_distances.rs, rascaline/src/calculators/tests_utils.rs, rascaline/src/descriptor/descriptor.rs, rascaline/src/descriptor/indexes/index.rs, rascaline/src/descriptor/indexes/mod.rs, rascaline/src/descriptor/indexes/samples.rs, rascaline/src/descriptor/indexes/species.rs, rascaline/src/descriptor/mod.rs
`Environment` only directly apply to "atom-centered" environments, and leave on the side descriptors with one sample per structure.
=> Finish renaming environments to samples everywhere

rascaline-c-api/src/calculator.rs, rascaline-c-api/src/system.rs, rascaline/benches/soap-power-spectrum.rs, rascaline/benches/spherical-expansion.rs, rascaline/examples/compute-soap.rs, rascaline/src/calculator.rs, rascaline/src/calculators/dummy_calculator.rs, rascaline/src/calculators/mod.rs, rascaline/src/calculators/soap/power_spectrum.rs, rascaline/src/calculators/soap/spherical_expansion.rs, rascaline/src/calculators/sorted_distances.rs, rascaline/src/calculators/tests_utils.rs, rascaline/src/descriptor/descriptor.rs, rascaline/src/descriptor/indexes/index.rs, rascaline/src/descriptor/indexes/samples.rs, rascaline/src/descriptor/indexes/species.rs, rascaline/src/system/test_utils.rs, rascaline/tests/data/mod.rs, rascaline/tests/soap-power-spectrum.rs, rascaline/tests/spherical-expansion.rs
Dealing with Boxed objects is more convenient that references, and this removes a lot of intermediary "references" vector from the C API
=> Use &mut [Box<dyn System>] instead of &mut [&mut dyn System]

python/rascaline/systems/ase.py, python/rascaline/systems/base.py, python/tests/ase_system.py, rascaline-c-api/include/rascaline.h, rascaline-c-api/include/rascaline.hpp, rascaline-c-api/src/system.rs, rascaline/src/systems/cell.rs, rascaline/src/types/matrix.rs
Most of the code already (incorrectly) assumed it, and it is the default in most (non fortran) codes
=> Use row-major representation for the unit cell matrix

docs/src/reference/python/calculators.rst, docs/src/reference/python/systems.rst, pyproject.toml, python/examples/compute-soap.py, python/rascaline/__init__.py, python/rascaline/calculators.py, python/rascaline/systems/__init__.py, python/rascaline/systems/ase.py, python/rascaline/systems/base.py, python/rascaline/systems/chemfiles.py, python/tests/calculators.py, python/tests/descriptor.py, python/tests/log.py, python/tests/systems/ase.py, python/tests/systems/chemfiles.py, python/tests/systems/errors.py, python/tests/test_systems.py, rascaline/src/calculators/dummy_calculator.rs, setup.py
Instead of using the Rust bindings through `BasicSystem`, make chemfiles' frames usable directly as a `System`. This should give users more flexibility.
=> Use Python's chemfiles bindings within Python bindings

.github/workflows/tests.yml, rascaline-c-api/CMakeLists.txt, rascaline-c-api/Cargo.toml, rascaline-c-api/tests/c-api.rs
This is usually easier to integrate with other C/C++ projects
=> Enable building the C API as a static library

rascaline/src/calculators/soap/power_spectrum.rs, rascaline/src/calculators/soap/spherical_expansion.rs, rascaline/src/calculators/sorted_distances.rs, rascaline/src/descriptor/descriptor.rs, rascaline/src/descriptor/indexes/mod.rs, rascaline/src/descriptor/indexes/species/mod.rs, rascaline/src/descriptor/indexes/species/structure.rs, rascaline/src/descriptor/indexes/species/three_bodies.rs, rascaline/src/descriptor/indexes/species/two_bodies.rs, rascaline/src/descriptor/mod.rs
It is more consistent with the ThreeBodiesSpeciesSamples implementation
=> Rename AtomSpeciesSamples to TwoBodiesSpeciesSamples

python/rascaline/calculators.py, python/tests/calculators.py
It can be used later if we want to change the hyper parameters: one can get `c_name` & `parameters`, change parameters & re-create a new calculator.
=> Store the name used to create the calculator in CalculatorBase

docs/src/reference/c/calculators.rst, python/rascaline/_rascaline.py, python/rascaline/calculators.py, rascaline-c-api/include/rascaline.h, rascaline-c-api/include/rascaline.hpp, rascaline-c-api/src/calculator.rs, rascaline-c-api/tests/c-api/calculator.cpp, rascaline-c-api/tests/c-api/cxx/calculator.cpp, rascaline/src/calculator.rs, rascaline/src/descriptor/indexes/samples.rs
This is useful for the torch integration, to create linear layers taking the features as output with known size. 
Unfortunately, there is no way to know the final number of features after calling `densify`, so this will not fully solve the issue above.
=> Add a function to get the number of features a calculator will produce

.gitignore, pyproject.toml, python/rascaline/clib.py, rascaline-c-api/CMakeLists.txt, setup.py
This removed duplication of functionalities such as disabling chemfiles
or using `@rpath/librascaline.dylib` as the link id on macOS
This also install headers & cmake configuration inside the python module,
allowing to use it to link another project (such as the pytorch integration)
with rascaline
=> Use the cmake build system to build the lib in python

.gitignore, MANIFEST.in, pyproject.toml, python/rascaline/__init__.py, python/rascaline/clib.py, python/tests/misc.py, rascaline-c-api/CMakeLists.txt, setup.cfg, setup.py
It brings more pain than is helpful. See the first commit message for more explanation.
Partially reverts #45, we are still using the cmake build system.
=> Do not use skbuild to build the Python module

python/rascaline/_rascaline.py, python/rascaline/descriptor.py, python/rascaline/systems/base.py, python/tests/descriptor.py, rascaline-c-api/Cargo.toml, rascaline-c-api/include/rascaline.h, rascaline-c-api/include/rascaline.hpp, rascaline-c-api/src/descriptor.rs, rascaline-c-api/tests/c-api/cxx/descriptor.cpp, rascaline-c-api/tests/c-api/descriptor.cpp, rascaline/src/descriptor/descriptor.rs
This will only densify the values of a descriptor, leaving the gradients untouched. This function is intended as an advanced feature, used to implement backward propagation without having to also densify the gradients array and use a lot of RAM storing zeros.
=> Add a `Descriptor::densify_values` function

.github/workflows/tests.yml, python/rascaline/clib.py, python/rascaline/log.py, rascaline-c-api/CMakeLists.txt, rascaline/Cargo.toml, rascaline/src/lib.rs, rascaline/src/types/stack_vec.rs
This is the version currently in Ubuntu 18.04, and a good minimal version to use (nalgebra wants 1.51). This PR also make sure the CI tests actually run with this version, previously the version was installed but stable was used for the tests.
=> Bump minimal rust version to 1.53

python/tests/calculators.py, rascaline-c-api/include/rascaline.h, rascaline-c-api/src/calculator.rs, rascaline-c-api/tests/c-api/calculator.cpp, rascaline/src/calculators/tests_utils.rs
The main use case is when we have a MD domain with no atoms inside, only "ghosts" atoms from neighboring domains
=> Allow to provide an empty set of selected sample/features

rascaline/src/calculators/soap/radial_integral/gto.rs
Change the comment according to the expression below eq. 10 of [Musil et. al](https://aip.scitation.org/doi/10.1063/5.0044689). The actual calculation in the code is correct.
=> Fixed little typo in comment for GTO width

rascaline-c-api/CMakeLists.txt, rascaline-c-api/Cargo.toml
It is now exposed in Cargo and CMake; and enabled when building the Python bindings
=> Manage the equistore/serialization feature

rascaline/src/calculators/lode/spherical_expansion.rs, rascaline/src/math/mod.rs
Added implementation for computing LODE structure factors. Basically adapted from pyLODE
```python
args = kvectors @ positions.T
cosines = np.cos(args)
sines = np.sin(args)
strucfac_real = np.zeros((num_kvecs, num_atoms, num_atoms))
strucfac_imag = np.zeros((num_kvecs, num_atoms, num_atoms))
for i in range(num_atoms):
for j in range(num_atoms):
strucfac_real[:, i, j] = cosines[:,i] * cosines[:,j] + sines[:,i] * sines[:,j]
strucfac_imag[:, i, j] = sines[:,i] * cosines[:,j] - cosines[:,i] * sines[:,j]
```
I will add some tests soon, but comments from @Luthaf on the code structure are appreciated.
=> Structure factors

rascaline/src/calculators/lode/gto_radial_integral.rs, rascaline/src/calculators/lode/mod.rs, rascaline/src/calculators/lode/radial_basis.rs, rascaline/src/calculators/lode/spherical_expansion.rs, rascaline/src/calculators/soap/gto_radial_integral.rs, rascaline/src/math/k_vectors.rs
This computes the radial integral and spherical harmonics for the k-vectors. The resulting values agree with pylode [`k_dep_factor_reordered`](https://github.com/ceriottm/lode/blob/fd2b88e3c8110c286bdb9a08908000c3dc0b4b58/src/pylode/lib/projection_coeffs.py#L346-L351) with `G_k` set to 1.0.
=> Implement projection of k-vectors to nlm

rascaline/src/calculators/soap/radial_integral/gto.rs
small comment for readers to highlight gamma calculations in SOAP radial integral because it is a bit hidden.
=> Added comment for gamma calculations

docs/src/reference/python/calculators.rst
Show all available calculators from the Python API without adding them explicitly.
=> Show all available python calculators

rascaline/src/calculators/soap/radial_integral/spline.rs, rascaline/src/math/mod.rs, rascaline/src/math/splines.rs
This make the spline re-usable across the project, and changes their output to an arbitrary array shape, opening the door to different radial resolution per angular channel in SOAP.
=> Extract the spline code into a standalone module

README.rst, docs/rascaline-json-schema/main.rs, docs/src/references/calculators/index.rst, docs/src/references/calculators/neighbor-list.rst, python/rascaline/__init__.py, python/rascaline/calculators.py, rascaline/src/calculator.rs, rascaline/src/calculators/mod.rs, rascaline/src/calculators/neighbor_list.rs
This allow to reduce rascaline role to a minimum, and only use it to extract data from atomistic systems. All subsequent calculations could then be written using PyTorch/JAX/...
A neighbor list is also useful when constructing message passing models, to know which atoms to include/exclude from the message passing step.
---
Ping @felixmusil, this might be another way of getting a NL for your pytorch models (once we finalize the rascaline <=> pytorch integration).
=> Add a neighbor list calculator

rascaline/src/calculators/lode/spherical_expansion.rs, rascaline/src/math/erf.rs, rascaline/src/math/exp.rs, rascaline/src/math/gamma.rs, rascaline/src/math/mod.rs
Fix even potential exponents `[2, 3, 4, 5, 6]` for LODE using an analytical expression for the gamma function over a powerlaw as @kvhuguenin is using them in pyLODE.
=> Fix potential exponents >1 for LODE

python/rascaline/_c_api.py, python/rascaline/calculators.py, python/tests/calculators.py, rascaline-c-api/include/rascaline.h, rascaline-c-api/src/calculator.rs, rascaline/src/calculator.rs, rascaline/src/calculators/dummy_calculator.rs, rascaline/src/calculators/lode/spherical_expansion.rs, rascaline/src/calculators/neighbor_list.rs, rascaline/src/calculators/soap/power_spectrum.rs, rascaline/src/calculators/soap/radial_spectrum.rs, rascaline/src/calculators/soap/spherical_expansion.rs, rascaline/src/calculators/sorted_distances.rs, rascaline/src/calculators/tests_utils.rs, rascaline/src/tutorials/moments/moments.rs, rascaline/src/tutorials/moments/s3_compute_3.rs, rascaline/src/tutorials/moments/s3_compute_4.rs, rascaline/src/tutorials/moments/s3_compute_5.rs
Hi all! This PR has added a new option `selected_keys` to the `compute` function. It allows the user to manually select the keys whose blocks will be computed by the algorithm. All relevant tests have been added.
=> Added selected_keys option to the compute function to allow manual selection of blocks for calculation

.github/workflows/tests.yml
With tox version 4 released our caching in the Github action does not work anymore because we created them with tox version 3.
To fix this this PR adds the tox major version as an additinal key for the Github action caching.
=> Use tox major version as additional key for cache

docs/src/how-to/index.rst, docs/src/how-to/keys-selection.rst, docs/src/how-to/property-selection.rst, python/examples/keys-selection.py
Hi all, this PR contains a how_to example for the new attribute of calculator `selected_keys`, added in #134
=> Add how_to on the keys selection

rascaline-c-api/src/lib.rs, rascaline-c-api/tests/utils/mod.rs, rascaline/benches/lode-spherical-expansion.rs, rascaline/benches/soap-power-spectrum.rs, rascaline/benches/soap-spherical-expansion.rs, rascaline/src/calculators/dummy_calculator.rs, rascaline/src/calculators/mod.rs, rascaline/src/calculators/soap/spherical_expansion.rs, rascaline/src/lib.rs, rascaline/src/systems/neighbors.rs, rascaline/tests/data/mod.rs, rascaline/tests/lode-madelung.rs
Previously, we where looking up block/sample/property for each pair and directly storing pair contributions into equistore. This lookup and accumulation was taking 4x longer than the calculation of pair contribution to the spherical expansion.
The new code accumulates data for all pairs first into temporary arrays, and later moves the data to equistore, making the spherical expansion up to 60% faster without gradients and 15% faster with gradients; while increasing the max RSS requirements by around 35%.
This was discovered while porting rascaline to use https://github.com/lab-cosmo/equistore/pull/85. I'll check that it does improve the results there as well before merging this PR!
<details>
```
group …
```
=> Reduce the number of equistore access in spherical expansion

docs/rascaline-json-schema/main.rs, docs/src/references/calculators/index.rst, docs/src/references/calculators/spherical-expansion-by-pair.rst, python/rascaline/__init__.py, python/rascaline/calculators.py, rascaline/src/calculator.rs, rascaline/src/calculators/mod.rs, rascaline/src/calculators/neighbor_list.rs, rascaline/src/calculators/soap/mod.rs, rascaline/src/calculators/soap/spherical_expansion.rs, rascaline/src/calculators/soap/spherical_expansion_pair.rs
This is only the first step, but I'm opening this since I've already re-written this code 3 times, so let's try to merge it before I have to rewrite it a fourth time!
This is currently in a state where the base code is shared between pair-by-pair calculation and full spx calculation, and the pair-by-pair code can compute the values (no gradients) of the spherical expansion.
---
Still TBD:
=> Add a pair-by-pair SOAP spherical expansion calculator

.github/workflows/tests.yml, AUTHORS, LICENSE, MANIFEST.in, docs/src/conf.py, setup.cfg, setup.py
As the other projects of our ecosystem (chemiscope, chemfiles, equistore, equisolve) rascaline should also use the BSD-3 license. This PRs adds the corresponding LICENSE file.
=> Add BSD-3 LICENSE file

.github/workflows/build-wheels.yml, .github/workflows/comment-wheels-pr.yml, .github/workflows/docs.yml, .github/workflows/tests.yml, .readthedocs.yml, CONTRIBUTING.rst, python/rascaline/splines.py, python/rascaline/systems/ase.py, python/scripts/build-wheels/Dockerfile, python/tests/splines.py, rascaline-c-api/Cargo.toml, rascaline/Cargo.toml, setup.cfg, tox.ini
As written in the title this updates the CI scripts to ensure them to work properly. To ensure this we have to bump the versions of glibc and rust.
=> Use glibc==2.28, rust==1.59, update GH actions and use py3.10 in CI

.github/workflows/tests.yml, CONTRIBUTING.rst, docs/rascaline-json-schema/Cargo.toml, python/rascaline/log.py, python/rascaline/systems/ase.py, python/rascaline/systems/chemfiles.py, rascaline-c-api/Cargo.toml, rascaline/Cargo.toml
This PR explicitly sets the `stacklevel` of warnings since this is required by [flake8](https://github.com/PyCQA/flake8-bugbear):
> B028: No explicit stacklevel keyword argument found. The warn method from the warnings module uses a stacklevel of 1 by default. This will only show a stack trace for the line on which the warn method is called. It is therefore recommended to use a stacklevel of 2 or greater to provide more information to the user.
Here, I set the level to `stacklevel=1` (the default) meaning that no additional backtrace information is given. I think we do not need more information for the user because the warnings are well written and a link and codeblock does not help much. If you disagree we can also set it to `2` or `3`.
=> Please B028 linter

.github/workflows/docs.yml
Read the docs [offers a GH new action](https://github.com/readthedocs/actions/tree/v1/preview) to post the link to the docs. This simplifies our workflow a bit.
----
:books: Documentation preview :books:: https://rascaline--163.org.readthedocs.build/en/163/
=> Use ReadtheDocs action for posting link to PR docs

.github/workflows/docs.yml, .github/workflows/documentation-links.yml
This is porting https://github.com/lab-cosmo/equistore/pull/167 to rascaline
=> Move the job posting RTD link to a separate workflow

.github/workflows/build-wheels.yml, python/scripts/build-wheels/Dockerfile, setup.py
We are always using libequistore.so from the corresponding Python package, and I just learned about the `--exclude` flag to `auditwheel repair`, which is intended for this exact use case.
----
:books: Documentation preview :books:: https://rascaline--170.org.readthedocs.build/en/170/
=> Do not include equistore in python wheels

docs/requirements.txt, python/rascaline/__init__.py, python/rascaline/_c_api.py, python/rascaline/_c_lib.py, python/rascaline/calculators.py, python/rascaline/profiling.py, python/rascaline/splines.py, python/rascaline/status.py, python/rascaline/systems/base.py, python/rascaline/utils.py, python/scripts/generate-declarations.py, python/tests/calculators.py, python/tests/log.py, python/tests/misc.py, python/tests/splines.py, python/tests/systems/ase.py, python/tests/systems/chemfiles.py, python/tests/systems/errors.py, python/tests/test_systems.py, rascaline-c-api/CMakeLists.txt, rascaline-c-api/cmake/rascaline-config.in.cmake, setup.py
This feature is used in rascaline-torch. This PR does three things:
- move `find_package(equistore)` to a later stage, otherwise it overwrites the `PACKAGE_PREFIX_DIR` variable
- do not include equistore cmake files in rascaline wheel
- add checks that the installation contains all the required files
----
:books: Documentation preview :books:: https://rascaline--172.org.readthedocs.build/en/172/
=> Improve usage of C library from installed Python package

rascaline/src/calculators/soap/cutoff.rs, rascaline/src/calculators/soap/spherical_expansion.rs, rascaline/src/calculators/soap/spherical_expansion_pair.rs
Hello,
for better compatibility with librascal I propose to allow the use of non-integer exponentials in the calculation of the
radial scaling functions.
----
:books: Documentation preview :books:: https://rascaline--196.org.readthedocs.build/en/196/
=> Allow for float exponentials in willatts radial scaling function

.github/workflows/tests.yml, .readthedocs.yml, CONTRIBUTING.rst, docs/rascaline-json-schema/Cargo.toml, rascaline-c-api/CMakeLists.txt, rascaline-c-api/Cargo.toml, rascaline/Cargo.toml
See https://github.com/lab-cosmo/equistore/pull/308
----
:books: Documentation preview :books:: https://rascaline--201.org.readthedocs.build/en/201/
=> Bump minimal Rustc version to 1.63

python/rascaline/rascaline/splines.py, rascaline/src/calculators/soap/radial_integral/spline.rs, rascaline/src/math/splines.rs
- Renaming `value` -> `values` and `derivative` -> `derivatives` in `spline.rs` to be consisted with the tabulated splining code.
- Test that exporting the spline points from `SoapRadialIntegralSpline::with_accuracy` and loading them into `SoapRadialIntegralSpline::from_tabulated` works directly. This test does not only checks that the two `struct`s are consistent but also that to methods create the same radial integrals.
- typehints in `spline.py` 
One thing that I found maybe improvable in the future is that we seem to use `gradients` and sometimes `derivatives` for the same thing. I try tried to improve this by using `derivatives` for everything that is related to the splines and `gradients` appears for the radial integral. But, maybe we can call everything `gradients`?
----
:books: …
=> Some consistency improvements to splining

.github/workflows/build-wheels.yml, .github/workflows/docs.yml, .github/workflows/tests.yml, .readthedocs.yml
Lifting the Python version in the CI to 3.11. Additionally I added a new CI job to test our minimal supported Python version.
----
:books: Documentation preview :books:: https://rascaline--208.org.readthedocs.build/en/208/
=> Newer Python version for upper bound CI test

rascaline-c-api/src/calculator.rs, rascaline-c-api/src/logging.rs, rascaline-c-api/src/system.rs, rascaline/src/calculators/soap/radial_integral/mod.rs
This is a follow up to #204.
----
:books: Documentation preview :books:: https://rascaline--211.org.readthedocs.build/en/211/
=> Warn instead of erroring if center_contribution is given to SOAP radial integral

rascaline/src/systems/cell.rs
Fix #215
Disallowing cells with a negative determinant seems to have been an oversight from me. I checked the neighbours list rascaline computes for all the structures in #215, and they all match the neighbor lists computed with ASE, so I think everything is fine? 
If someone knows more about this kind of cell, feel free to chime in! I've never seen such cells before, but they look legit.
----
:books: Documentation preview :books:: https://rascaline--216.org.readthedocs.build/en/216/
=> Allow cell matrix to have a negative determinant

python/rascaline/rascaline/utils/power_spectrum.py, python/rascaline/tests/utils/power_spectrum.py
Possible fix for #213.
This adds the option `fill_species_neighbor ` to the compute method of  `PowerSpectrum`. Setting this to `True` changes `keys_to_move` when performing `keys_to_properties` in such a way that it contains all species of the provided systems.
I am not super happy with the name of the parameter but I think the it should be part of the the compute method.
----
:books: Documentation preview :books:: https://rascaline--214.org.readthedocs.build/en/214/
=> Add option to fill all species  when computing `PowerSpectrum` 

docs/src/conf.py, docs/src/references/api/torch/index.rst, docs/src/references/api/torch/utils/index.rst, docs/src/references/api/torch/utils/power-spectrum.rst, python/rascaline-torch/rascaline/torch/calculator_base.py, python/rascaline-torch/rascaline/torch/calculators.py, python/rascaline-torch/rascaline/torch/utils/__init__.py, python/rascaline-torch/rascaline/torch/utils/power_spectrum.py, python/rascaline-torch/tests/calculator.py, python/rascaline-torch/tests/utils/power_spectrum.py, python/rascaline/rascaline/calculator_base.py, python/rascaline/rascaline/utils/power_spectrum/__init__.py, python/rascaline/rascaline/utils/power_spectrum/_classes.py, python/rascaline/rascaline/utils/power_spectrum/_dispatch.py, python/rascaline/rascaline/utils/power_spectrum/calculator.py
----
:books: Documentation preview :books:: https://rascaline--220.org.readthedocs.build/en/220/
=> Make Python PS torch compatible

.github/workflows/torch-tests.yml, docs/requirements.txt, pyproject.toml, python/rascaline-torch/pyproject.toml, rascaline-c-api/CMakeLists.txt, rascaline-c-api/Cargo.toml, rascaline-c-api/src/calculator.rs, rascaline-c-api/src/status.rs, rascaline-c-api/tests/catch/CMakeLists.txt, rascaline-torch/CMakeLists.txt, rascaline-torch/tests/utils/mod.rs, rascaline/Cargo.toml, rascaline/src/calculators/neighbor_list.rs, rascaline/src/calculators/soap/spherical_expansion.rs, tox.ini
----
:books: Documentation preview :books:: https://rascaline--243.org.readthedocs.build/en/243/
=> Updates for PyTorch 2.1

rascaline/src/calculators/lode/spherical_expansion.rs
Subtraction theorem exploited when computing the LODE structure factor in order to remove the double sum over atoms.
----
:books: Documentation preview :books:: https://rascaline--242.org.readthedocs.build/en/242/
=> subtraction theorem exploited in LODE structure factor

CONTRIBUTING.rst, docs/src/get-started/installation.rst, rascaline-c-api/tests/CMakeLists.txt, rascaline-torch/tests/CMakeLists.txt
This basically bring to rascaline things we are already doing in metatensor.
----
:books: Documentation preview :books:: https://rascaline--244.org.readthedocs.build/en/244/
=> Some improvements to dev tools & documentation

.github/workflows/rust-tests.yml, .readthedocs.yml, CONTRIBUTING.rst, docs/rascaline-json-schema/Cargo.toml, python/scripts/rustc-manylinux2014_x86_64/Dockerfile, rascaline-c-api/Cargo.toml, rascaline/Cargo.toml
----
:books: Documentation preview :books:: https://rascaline--245.org.readthedocs.build/en/245/
=> Bump rustc to 1.65

.codecov.yml, .github/workflows/coverage.yml, .gitignore, CONTRIBUTING.rst, tox.ini
Using the same logic and structure as https://github.com/lab-cosmo/metatensor/pull/381.
----
:books: Documentation preview :books:: https://rascaline--234.org.readthedocs.build/en/234/
=> Add coverage for Python torch bindings

pyproject.toml, python/rascaline-torch/build-backend/backend.py, python/rascaline-torch/setup.py, setup.py
Trying to run `pip install .[torch]` from source will fail with an error like this:
```
INFO: pip is looking at multiple versions of metatensor-torch to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install rascaline-torch, rascaline==0.1.0.dev457 and rascaline[torch]==0.1.0.dev457 because these package versions have conflicting dependencies.
The conflict is caused by:
rascaline[torch] 0.1.0.dev457 depends on metatensor-core 0.1.0 (from https://github.com/lab-cosmo/metatensor/archive/d97ea65.zip#subdirectory=python/metatensor-core)
rascaline 0.1.0.dev457 depends on metatensor-core 0.1.0 (from https://github.com/lab-cosmo/metatensor/archive/d97ea65.zip#subdirectory=python/metatensor-core)
metatensor-torch 0.1.0 depends on …
```
=> Make rascaline-torch an optional dependency of rascaline

python/rascaline/rascaline/utils/power_spectrum/calculator.py, rascaline/src/calculators/soap/power_spectrum.rs, rascaline/tests/soap-power-spectrum.rs, scripts/clean-python.sh
This make the power spectrum produce the same output as doing a full Clebsch-Gordan product and keeping only the lambda=0 term
----
:books: Documentation preview :books:: https://rascaline--248.org.readthedocs.build/en/248/
=> Add a (-1)^l factor to the power spectrum invariants

rascaline/src/calculators/lode/radial_integral/mod.rs, rascaline/src/calculators/lode/radial_integral/spline.rs
Fixes #249 
The `cutoff` for the LODE `TabulatedRadialIntegral ` was set to real space environment  cutoff. This is wrong since for LODE we spline in k-space from 0 until the `k_cutoff`.
----
:books: Documentation preview :books:: https://rascaline--250.org.readthedocs.build/en/250/
=> fix `cutoff` in LODE `TabulatedRadialIntegral`

python/rascaline-torch/tests/calculator.py, rascaline-torch/include/rascaline/torch/calculator.hpp, rascaline-torch/src/register.cpp
We need to store the registration name, not the self-reported calculator name
----
:books: Documentation preview :books:: https://rascaline--254.org.readthedocs.build/en/254/
=> Fix serialization of calculators in torch

docs/src/explanations/concepts.rst, python/rascaline/examples/compute-soap.py, python/rascaline/examples/keys-selection.py, python/rascaline/examples/property-selection.py, python/rascaline/rascaline/utils/clebsch_gordan/_cg_cache.py, python/rascaline/rascaline/utils/clebsch_gordan/_clebsch_gordan.py, python/rascaline/rascaline/utils/clebsch_gordan/_dispatch.py, python/rascaline/rascaline/utils/clebsch_gordan/correlate_density.py, python/rascaline/rascaline/utils/splines/atomic_density.py, python/rascaline/tests/utils/rotations.py, python/rascaline/tests/utils/splines.py
----
📚 Documentation preview 📚: https://rascaline--275.org.readthedocs.build/en/275/
=> fix broken metatensor documentation links

docs/src/references/api/c/misc.rst, docs/src/references/api/cxx/misc.rst, docs/src/references/api/python/misc.rst
----
📚 Documentation preview 📚: https://rascaline--276.org.readthedocs.build/en/276/
=> Fix "miscelaneous" typo

python/rascaline-torch/tests/autograd.py, python/rascaline-torch/tests/calculator.py, rascaline-c-api/CMakeLists.txt, rascaline-torch/CMakeLists.txt, rascaline-torch/src/autograd.cpp, rascaline-torch/src/calculator.cpp, rascaline-torch/src/system.cpp
All calculations still happen on CPU with 64-bit floats, but the data is automatically converted on input and output as required.
Should help with https://github.com/lab-cosmo/metatensor-models/pull/58
----
📚 Documentation preview 📚: https://rascaline--278.org.readthedocs.build/en/278/
=> Use the input dtype and device for the output in rascaline-torch

rascaline-c-api/CMakeLists.txt
This should fix the build error with ahash on older rustc.
----
📚 Documentation preview 📚: https://rascaline--282.org.readthedocs.build/en/282/
=> Use metatensor v0.1.3

python/rascaline/rascaline/systems/ase.py, python/rascaline/tests/systems/ase.py, rascaline/src/calculators/neighbor_list.rs, rascaline/src/calculators/soap/spherical_expansion.rs, rascaline/src/calculators/soap/spherical_expansion_pair.rs, rascaline/src/systems/neighbors.rs
This was found by @liam-o-marsh in #240, and I cherry-picked it to merge the fix quicker. 
Ping @rosecers who wants to use this!
----
:books: Documentation preview :books:: https://rascaline--260.org.readthedocs.build/en/260/
=> Fixed double-counting of periopdic image pairs

rascaline/src/math/splines.rs
----
📚 Documentation preview 📚: https://rascaline--289.org.readthedocs.build/en/289/
=> Print spline convergence information as `debug` instead of `info`

python/rascaline-torch/setup.py, rascaline-c-api/tests/utils/mod.rs, setup.py
We use cmake's `--parallel` flag to speed up compilation for Python builds
----
📚 Documentation preview 📚: https://rascaline--292.org.readthedocs.build/en/292/
=> Parallelize compilation with cmake

rascaline/src/calculator.rs, rascaline/src/calculators/neighbor_list.rs
simple python test:
```python
import pyscf, rascaline
mol = rascaline.systems.wrap_system(pyscf.M(atom='H 0 0 -10; H 0 0 10'))
rascaline.calculators.NeighborList(5.0,False).compute(mol)
```
Since the cutoff is smaller than the distance between hydrogens, there are no pairs found by `compute_neighbors`, causing `assert_ne!(keys.count(), 0);` to panic (at `rascaline/src/calculator.rs:59:9`).
Those three lines prevent the panic by making `Calculator::prepare()` return an empty TensorMap early.
----
📚 Documentation preview 📚: https://rascaline--308.org.readthedocs.build/en/308/
=> temptative fix for the case where a calculator does not return anything

python/rascaline/rascaline/utils/clebsch_gordan/correlate_density.py
Just some minor changes to make it look nicer.
----
📚 Documentation preview 📚: https://rascaline--311.org.readthedocs.build/en/311/
=> Fix formatting of documentation for DensityCorrelations

.github/workflows/build-wheels.yml, .github/workflows/python-tests.yml, .github/workflows/rust-tests.yml
----
📚 Documentation preview 📚: https://rascaline--313.org.readthedocs.build/en/313/
=> Don't use macos-11 runners on CI, they are deprecated

docs/src/devdoc/how-to/new-calculator.rst, docs/src/references/api/python/utils/clebsch-gordan.rst, python/rascaline-torch/rascaline/torch/calculator_base.py, python/rascaline-torch/rascaline/torch/system.py, python/rascaline-torch/rascaline/torch/utils.py, python/rascaline-torch/tests/utils/cartesian_spherical.py, python/rascaline/rascaline/calculator_base.py, python/rascaline/rascaline/utils/__init__.py, python/rascaline/rascaline/utils/_backend.py, python/rascaline/rascaline/utils/_dispatch.py, python/rascaline/rascaline/utils/clebsch_gordan/__init__.py, python/rascaline/rascaline/utils/clebsch_gordan/_cartesian_spherical.py, python/rascaline/rascaline/utils/clebsch_gordan/_coefficients.py, python/rascaline/rascaline/utils/clebsch_gordan/_correlate_density.py, python/rascaline/rascaline/utils/power_spectrum.py, python/rascaline/rascaline/utils/splines/splines.py, python/rascaline/tests/utils/cartesian_spherical.py, python/rascaline/tests/utils/correlate_density.py, tox.ini
This PR implements a function to transform a TensorMap from cartesian product basis to a spherical basis.
Still TBD:
----
📚 Documentation preview 📚: https://rascaline--315.org.readthedocs.build/en/315/
=> Cartesian to spherical

rascaline/src/calculator.rs
Instead we can exploit the underlying HashMap structure of Labels.
Fixes #319, bringing the calculation down to 2.5s on my machine. There might be more optimizations to do here, but at least the worst issue is gone.
```
╔════╦══════════════════════════════════════════════╦════════════╦═══════════╦══════════╦══════════╗
║ id ║ span name                                    ║ call count ║ called by ║ total    ║ mean     ║
╠════╬══════════════════════════════════════════════╬════════════╬═══════════╬══════════╬══════════╣
║  1 ║ Calculator::prepare                          ║          1 ║         — ║    1.65s ║    1.65s ║
╠════╬══════════════════════════════════════════════╬════════════╬═══════════╬══════════╬══════════╣
║  0 ║ NeighborsList                                ║          1 ║ …
```
=> Make Labels selection not O(n^2)

docs/src/conf.py
Metatensor docs changed links?
----
📚 Documentation preview 📚: https://rascaline--324.org.readthedocs.build/en/324/
=> Update intersphinx for metatensor

python/rascaline/rascaline/utils/clebsch_gordan/_coefficients.py
Moving the mu dimension first means that individual iterations store data close together in memory.
This makes a test with EquivariantPowerSpectrum from #329 go from 1.8s to 1.1s on my machine. Still horribly slow overall, but a step in the right direction.
----
📚 Documentation preview 📚: https://rascaline--330.org.readthedocs.build/en/330/
=> Speedup `_cg_couple_sparse` a bit

.github/workflows/build-wheels.yml, .github/workflows/coverage.yml, .github/workflows/docs.yml, .github/workflows/python-tests.yml, .github/workflows/rust-tests.yml, .github/workflows/torch-tests.yml, CONTRIBUTING.rst, README.rst
This should contain all code changes necessary to rename `master` to `main`
----
📚 Documentation preview 📚: https://rascaline--335.org.readthedocs.build/en/335/
=> Rename `master` to `main` in code

docs/src/explanations/rotation_adapted.rst
If it were real, we would need m1 and m2 indices
----
📚 Documentation preview 📚: https://rascaline--340.org.readthedocs.build/en/340/
=> Fix inaccuracy in `rotation_adapted.rst`

featomic-torch/CMakeLists.txt, featomic-torch/cmake/dev-versions.cmake, featomic-torch/tests/cmake-project/CMakeLists.txt, featomic/CMakeLists.txt, featomic/cmake/dev-versions.cmake, featomic/tests/cmake-project/CMakeLists.txt
When building featomic-torch, we need to create development version differently for featomic and featomic-torch.
Follow up to #348 
----
📚 Documentation preview 📚: https://featomic--354.org.readthedocs.build/en/354/
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/metatensor/featomic/actions/artifacts/2274689056.zip)
=> Use the correct tag prefix for featomic dependency

.github/workflows/build-wheels.yml, .github/workflows/python-tests.yml, .github/workflows/rust-tests.yml, .github/workflows/torch-tests.yml
----
📚 Documentation preview 📚: https://featomic--368.org.readthedocs.build/en/368/
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/metatensor/featomic/actions/artifacts/2402276753.zip)
=> Bump to windows-2022

.github/workflows/rust-tests.yml
`!FOOBAR` is special YAML syntax, so we need to put this inside a string. I'm not sure why CI did not catch this.
----
📚 Documentation preview 📚: https://featomic--369.org.readthedocs.build/en/369/
=> Fix YAML syntax for rust tests

python/featomic/featomic/clebsch_gordan/_equivariant_power_spectrum.py, python/featomic/tests/clebsch_gordan/equivariant_power_spectrum.py
Adds sample selection to the equivariant power spectrum convenience class.
=> Adds sample selection to equivariant power spectrum

featomic-torch/CHANGELOG.md, featomic-torch/tests/cmake-project/CMakeLists.txt
Patch release that includes new builds for Python 3.13 and Pytorch 2.6.
[📚 Download documentation for this pull-request](https://nightly.link/metatensor/featomic/actions/artifacts/2611539400.zip)
[⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/metatensor/featomic/actions/artifacts/2611643510.zip)
=> Release featomic-torch v0.6.1

docs/src/how-to/computing-lambda-soap.rst, docs/src/how-to/density-correlations.rst, docs/src/how-to/index.rst, docs/src/how-to/per-pair-equivariant-features.rst, python/featomic/examples/compute-lambda-soap.py, python/featomic/examples/density-correlations.py, python/featomic/examples/per-pair-equivariant-features.py, tox.ini
[📚 Download documentation for this pull-request](https://nightly.link/metatensor/featomic/actions/artifacts/3528031245.zip)
=> Tutorials for high-level calculators from the `clebsch_gordan` module
