metatensor/featomic

.github/workflows/docs.yml, .github/workflows/tests.yml, rascaline/src/calculators/soap/radial_integral.rs, rascaline/tests/spherical-expansion.rs
This should help making sure the code builds & run on all platforms =)
=> Setup github actions

rascaline-c-api/tests/c-api.rs, rascaline-c-api/tests/python-api.rs, rascaline-c-api/tests/utils.rs
=> Check that commands exists before calling them in tests

.github/workflows/tests.yml, python/rascaline/_rascaline.py, python/rascaline/calculator.py, python/rascaline/descriptor.py, python/scripts/generate-declarations.py, python/scripts/include/stdint.h, python/tests/calculators.py, python/tests/descriptor.py, rascaline-c-api/rascaline.h, rascaline-c-api/src/calculator.rs, rascaline-c-api/src/descriptor.rs, rascaline-c-api/tests/c-api/calculator.cpp, rascaline-c-api/tests/c-api/descriptor.cpp, rascaline/Cargo.toml, rascaline/src/calculator.rs, rascaline/src/calculators/dummy_calculator.rs, rascaline/src/calculators/soap/power_spectrum.rs, rascaline/src/calculators/soap/radial_integral/gto.rs, rascaline/src/calculators/soap/radial_integral/spline.rs, rascaline/src/calculators/soap/spherical_expansion.rs, rascaline/src/calculators/soap/spherical_harmonics.rs, rascaline/src/calculators/sorted_distances.rs, rascaline/src/descriptor/descriptor.rs, rascaline/src/descriptor/indexes/environments.rs, rascaline/src/descriptor/indexes/index.rs, rascaline/src/descriptor/indexes/species.rs, rascaline/src/system/simple_system.rs
This PR brings Spherical expansion calculation and power spectrum on par with librascal. This code still takes a bit more time to do the full computation when building the set of indexes for environments.
=> Optimize Spherical expansion & power spectrum

.github/workflows/tests.yml
This should make CI run faster overall.
=> Separate debug & release build in CI

rascaline-c-api/tests/c-api/CMakeLists.txt, rascaline-c-api/tests/c-api/valgrind.supp, rascaline/Cargo.toml, rascaline/examples/compute-soap.rs, rascaline/src/calculators/soap/power_spectrum.rs, rascaline/src/calculators/soap/radial_integral/mod.rs, rascaline/src/calculators/soap/spherical_expansion.rs, rascaline/src/calculators/tests_utils.rs, rascaline/src/types/mod.rs, rascaline/src/types/stack_vec.rs
The strategy used is to parallelize over pairs for spherical expansion, and accumulate samples in parrallel for the power spectrum. Most of the parallelism comes from [rayon](https://docs.rs/rayon/1.5.0/rayon/) operations.
There is a cost to the parallel infrastructure, with benchmarks with low n_max/l_max being up to 4 times slower, while benchmarks with high n_max/l_max are up to 30% faster!
<details>
```
group                                                                                      1-thread                 master
-----                                                                                      --------                 ------
Spherical expansion (per atom) with gradients/Bulk Silicon/n_max = 14, l_max = 1           1.48     96.2±1.60µs     1.00     64.8±0.78µs …
```
=> Multithreaded calculation of spherical expansion and power spectrum

rascaline/benches/soap-power-spectrum.rs, rascaline/benches/spherical-expansion.rs, rascaline/src/calculator.rs, rascaline/src/calculators/dummy_calculator.rs, rascaline/src/calculators/mod.rs, rascaline/src/calculators/soap/power_spectrum.rs, rascaline/src/calculators/soap/spherical_expansion.rs, rascaline/src/calculators/sorted_distances.rs, rascaline/src/descriptor/descriptor.rs, rascaline/src/descriptor/indexes/index.rs, rascaline/src/descriptor/indexes/mod.rs, rascaline/src/descriptor/indexes/samples.rs, rascaline/src/descriptor/indexes/species/structure.rs, rascaline/src/descriptor/indexes/species/three_bodies.rs, rascaline/src/descriptor/indexes/species/two_bodies.rs, rascaline/src/descriptor/mod.rs
And add a bit of documentation around it.
=> Rename SampleIndexes to SampleBuilder

rascaline/src/calculators/soap/power_spectrum.rs, rascaline/src/calculators/soap/spherical_expansion.rs, rascaline/tests/spherical-expansion.rs
This makes it easier to treat spherical expansion as an equivariant
=> Store spherical expansion features as lmn instead of nlm

python/rascaline/__init__.py, python/rascaline/calculators.py, python/rascaline/profiling.py, python/tests/calculators.py, rascaline-c-api/include/rascaline.hpp, rascaline-c-api/src/descriptor.rs, rascaline-c-api/tests/c-api/calculator.cpp, rascaline-c-api/tests/c-api/cxx/calculator.cpp
=> Also allow accessing empty indexes from C/C++

python/rascaline/__init__.py, rascaline/src/calculators/lode/spherical_expansion.rs, rascaline/src/math/kvectors.rs, rascaline/src/math/mod.rs
Added computation of k vectors for LODE calculations. I will add the tests but if @Luthaf or @kvhuguenin already have ideas please let me know.
=> Implemenet k-vector computation

setup.cfg, setup.py
Tiny change which saves some lines :-)
=> Move python version check to setup.cfg

.github/workflows/docs.yml, .readthedocs.yml, docs/extensions/rascaline_json_schema.py
=> Read the docs deploy

python/scripts/build-wheels/Dockerfile, rascaline-c-api/Cargo.toml, rascaline-c-api/include/equistore.hpp, rascaline-c-api/include/rascaline.hpp, rascaline-c-api/tests/c-api/cxx/calculator.cpp, rascaline/Cargo.toml, setup.cfg, tox.ini
As part of the update, this makes the C++ `LabelsSelection` copyable by storing inner data as shared pointers
=> Update equistore to recent version

docs/src/how-to/feature-selection.rst, docs/src/how-to/index.rst, docs/src/how-to/property-selection.rst, docs/src/how-to/sample-selection.rst, python/examples/property-selection.py, python/examples/sample-selection.py
Solution of the #86 
Below are small guides on how to use sample and feature selection in rascaline. The example is made in agreement with a tutorial already available.
=> Added how-to on the topics feature selection and sample selection

rascaline/src/calculators/soap/spherical_expansion.rs
These samples will be left at 0, but this is useful to make some calculations simpler in Python.
Previously, the center contribution was added to the values array even if the sample corresponded to a non-existing atom/an atom with the wrong species
~This builds on top of #121.~
=> Allow requesting more samples in spherical expansion

.github/workflows/comment-wheels-pr.yml, .github/workflows/docs.yml, .github/workflows/tests.yml, README.rst, rascaline-c-api/CMakeLists.txt, tox.ini
Equilizes with the equistore GH infrastrcuture
* Add GH-action for posting Python wheels
* Use py310 in GH tests & docs
* Update build command in tox.ini
* Update docs link in README.rst
=> Infrastructure Updates

rascaline/benches/spherical-harmonics.rs, rascaline/src/calculators/soap/mod.rs, rascaline/src/calculators/soap/radial_integral/mod.rs, rascaline/src/calculators/soap/spherical_expansion.rs, rascaline/src/lib.rs, rascaline/src/math/gamma.rs, rascaline/src/math/mod.rs, rascaline/src/math/spherical_harmonics.rs, rascaline/tests/spherical-harmonics.rs
These will also be used by LODE and the spherical expansion by pair
=> Refactor SphericalHarmonicsCache and RadialIntegralCache out of the spherical expansion code

rascaline/src/calculators/neighbor_list.rs, rascaline/src/calculators/soap/spherical_expansion_pair.rs
This is a follow-up to #147. 
Previously, the samples would look like this
```
structure, pair_id, first_atom, second_atom
0          1         1           0
0          1         0           1
0          2         1           2
0          2         2           1
1          1         1           0
1          1         0           1
...
0         -1         0           0
0         -1         1           1
0         -1         2           2
1         -1         0           0
1         -1         1           1
```
i.e; with the "self" pairs at the end of the samples, meaning there could be a jump in the "structure" sample. This changes it to group all structures, placing the "self" pairs first inside the samples for a given structure.
=> Change the order of samples in spherical exansion by pair

python/scripts/build-wheels/Dockerfile, rascaline-c-api/Cargo.toml, rascaline/Cargo.toml
This is a follow up to #155, and the mirror of https://github.com/lab-cosmo/equistore/pull/131 for rascaline
----
:books: Documentation preview :books:: https://rascaline--166.org.readthedocs.build/en/166/
=> Use manylinux_2010 to build wheels

docs/requirements.txt, docs/src/conf.py, docs/src/how-to/property-selection.rst, python/examples/property-selection.py
Addressing #168 
----
:books: Documentation preview :books:: https://rascaline--176.org.readthedocs.build/en/176/
=> Fixing scikit-cosmo

python/rascaline/systems/base.py
Clarify the documentation, and use np.asarray to avoid unnecessary copies
----
:books: Documentation preview :books:: https://rascaline--180.org.readthedocs.build/en/180/
=> Small improvements to SystemBase

rascaline/src/calculators/lode/radial_integral/gto.rs, rascaline/src/calculators/soap/power_spectrum.rs, rascaline/src/calculators/soap/radial_integral/gto.rs
----
:books: Documentation preview :books:: https://rascaline--182.org.readthedocs.build/en/182/
=> Misc small improvements

rascaline/src/calculators/soap/power_spectrum.rs, rascaline/src/systems/test_utils.rs
The cell gradients where already doing the right thing.
----
:books: Documentation preview :books:: https://rascaline--186.org.readthedocs.build/en/186/
=> Fix positions gradients of SOAP PS with more than two species

.github/workflows/tests.yml, docs/requirements.txt, rascaline-c-api/CMakeLists.txt, rascaline-c-api/Cargo.toml, rascaline/Cargo.toml, setup.cfg, tox.ini
Pulled out of #158 in case I need to force push a lot to get CI to pass
----
:books: Documentation preview :books:: https://rascaline--188.org.readthedocs.build/en/188/
=> Update equistore-core to 3bced4c

rascaline-c-api/include/rascaline.hpp, rascaline-c-api/tests/cxx/calculator.cpp, rascaline-c-api/tests/cxx/systems.cpp, setup.py
This PR contains a handful of small changes/cleanup unrelated to rascaline-torch but that should happen before the code moves to it's new home.
----
:books: Documentation preview :books:: https://rascaline--199.org.readthedocs.build/en/199/
=> Multiple improvements to prepare for rascaline-torch moving day

docs/src/devdoc/how-to/new-calculator.rst, docs/src/references/api/c/calculators.rst, python/rascaline/rascaline/_c_api.py, python/rascaline/rascaline/calculators.py, python/rascaline/tests/calculators/dummy_calculator.py, python/scripts/generate-declarations.py, rascaline-c-api/include/rascaline.h, rascaline-c-api/include/rascaline.hpp, rascaline-c-api/src/calculator.rs, rascaline-c-api/tests/calculator.cpp, rascaline-c-api/tests/cxx/calculator.cpp, rascaline/src/calculator.rs, rascaline/src/calculators/atomic_composition.rs, rascaline/src/calculators/dummy_calculator.rs, rascaline/src/calculators/lode/spherical_expansion.rs, rascaline/src/calculators/mod.rs, rascaline/src/calculators/neighbor_list.rs, rascaline/src/calculators/soap/power_spectrum.rs, rascaline/src/calculators/soap/radial_spectrum.rs, rascaline/src/calculators/soap/spherical_expansion.rs, rascaline/src/calculators/soap/spherical_expansion_pair.rs, rascaline/src/calculators/sorted_distances.rs, rascaline/src/tutorials/moments/moments.rs, rascaline/src/tutorials/moments/s1_scaffold.rs, rascaline/src/tutorials/moments/s2_metadata.rs, rascaline/src/tutorials/moments/s3_compute_1.rs, rascaline/src/tutorials/moments/s3_compute_2.rs, rascaline/src/tutorials/moments/s3_compute_3.rs, rascaline/src/tutorials/moments/s3_compute_4.rs, rascaline/src/tutorials/moments/s3_compute_5.rs
This will be required for the LAMMPS interface
----
:books: Documentation preview :books:: https://rascaline--203.org.readthedocs.build/en/203/
=> Allow to extract the list of cutoffs from a calculator

rascaline/src/calculators/lode/radial_integral/mod.rs, rascaline/src/calculators/lode/radial_integral/spline.rs, rascaline/src/calculators/radial_basis/mod.rs, rascaline/src/calculators/soap/radial_integral/mod.rs, rascaline/src/calculators/soap/radial_integral/spline.rs
This is a WIP work and currently works but doesn't support the `central_atom_contribution`
=> Enable splines for LODE

.github/workflows/coverage.yml, .github/workflows/docs.yml, .github/workflows/python-tests.yml, .github/workflows/rust-tests.yml
----
:books: Documentation preview :books:: https://rascaline--209.org.readthedocs.build/en/209/
=> Split Python and Rust/C/C++ tests in CI

rascaline-c-api/CMakeLists.txt, rascaline-c-api/cmake/rascaline-config.in.cmake, rascaline-c-api/include/rascaline.hpp, rascaline-c-api/tests/calculator.cpp, rascaline-c-api/tests/cxx/calculator.cpp
Fix #142, will be used in #200
----
:books: Documentation preview :books:: https://rascaline--207.org.readthedocs.build/en/207/
=> Expose key selections to the C++ interface

docs/requirements.txt, python/rascaline/rascaline/systems/base.py
Related to #18, only for Python in this case.
----
:books: Documentation preview :books:: https://rascaline--217.org.readthedocs.build/en/217/
=> Add an example of how to use SystemBase

rascaline/src/calculators/lode/radial_integral/gto.rs, rascaline/src/calculators/soap/radial_integral/gto.rs
Fix #122
----
:books: Documentation preview :books:: https://rascaline--228.org.readthedocs.build/en/228/
=> Better validation of cutoff & atomic_gaussian_width

python/rascaline-torch/rascaline/torch/system.py, python/rascaline-torch/tests/system.py
----
:books: Documentation preview :books:: https://rascaline--229.org.readthedocs.build/en/229/
=> Fix systems bug

python/rascaline/rascaline/utils/splines.py
Just some leftover comments from #212.
----
:books: Documentation preview :books:: https://rascaline--233.org.readthedocs.build/en/233/
=> Small docs changes in splines

tox.ini
----
:books: Documentation preview :books:: https://rascaline--252.org.readthedocs.build/en/252/
=> Disable coverage reporting in terminal

python/rascaline/rascaline/systems/__init__.py, python/rascaline/rascaline/systems/pyscf.py, python/rascaline/tests/systems/pyscf.py, tox.ini
----
:books: Documentation preview :books:: https://rascaline--263.org.readthedocs.build/en/263/
=> added pyscf system

rascaline-c-api/CMakeLists.txt, rascaline-c-api/cmake/tempdir.cmake
This is similar to https://github.com/lab-cosmo/metatensor/pull/438
----
📚 Documentation preview 📚: https://rascaline--272.org.readthedocs.build/en/272/
=> Fix build with cargo 1.75

docs/src/how-to/index.rst, docs/src/how-to/le-basis.rst, docs/src/how-to/splined-radial-integral.rst, python/rascaline/examples/le-basis.py, python/rascaline/examples/splined-radial-integral.py, python/rascaline/rascaline/utils/splines/radial_basis.py, python/rascaline/rascaline/utils/splines/splines.py, python/rascaline/tests/utils/radial_basis.py
Also fixes #258 
----
:books: Documentation preview :books:: https://rascaline--257.org.readthedocs.build/en/257/
=> LE basis example

docs/src/get-started/installation.rst, python/rascaline/examples/le-basis.py, python/rascaline/examples/splined-radial-integral.py
Fix #279 
----
📚 Documentation preview 📚: https://rascaline--286.org.readthedocs.build/en/286/
=> Update installation instructions with the new nightly wheels

.github/workflows/coverage.yml, .github/workflows/docs.yml, .github/workflows/python-tests.yml
Similar to https://github.com/lab-cosmo/metatensor/pull/543
----
📚 Documentation preview 📚: https://rascaline--290.org.readthedocs.build/en/290/
=> Pin tox v4.14.0

rascaline/src/calculators/lode/spherical_expansion.rs
This is only used when we have fewer systems than available threads.
For many system, this is between 5% slower and 20% faster than the previous code (likely due to the reorganization of the loop over samples). For a single system, this is up to 6x faster with 10 threads for the molecular_crystal benchmark file.
Requested by @andreagrisafi for use in SALTED!
----
📚 Documentation preview 📚: https://rascaline--293.org.readthedocs.build/en/293/
=> Parallelize LODE calculation over samples

.github/workflows/torch-tests.yml, docs/requirements.txt, python/rascaline-torch/build-backend/backend.py, python/rascaline-torch/setup.py, python/rascaline-torch/tests/export.py, rascaline-torch/CMakeLists.txt, tox.ini
----
📚 Documentation preview 📚: https://rascaline--297.org.readthedocs.build/en/297/
=> Update to metatensor torch v0.4.0

.github/workflows/build-wheels.yml, .github/workflows/docs.yml, .github/workflows/python-tests.yml, .github/workflows/rust-tests.yml, .github/workflows/torch-tests.yml, docs/requirements.txt, python/rascaline-torch/build-backend/backend.py, python/rascaline-torch/rascaline/torch/calculator_base.py, python/rascaline-torch/setup.py, python/rascaline-torch/tests/export.py, rascaline-c-api/CMakeLists.txt, rascaline-c-api/src/calculator.rs, rascaline-c-api/src/lib.rs, rascaline-c-api/src/system.rs, rascaline-torch/CMakeLists.txt, rascaline-torch/src/system.cpp, rascaline-torch/tests/utils/mod.rs, rascaline-torch/tests/valgrind.supp, rascaline/src/calculator.rs, rascaline/src/calculators/lode/radial_integral/gto.rs, rascaline/src/calculators/lode/spherical_expansion.rs, rascaline/src/calculators/soap/radial_integral/gto.rs, rascaline/src/calculators/soap/spherical_expansion.rs, setup.py, tox.ini
----
📚 Documentation preview 📚: https://rascaline--303.org.readthedocs.build/en/303/
=> Update to metatensor-torch v0.5.0

python/rascaline-torch/tests/export.py, rascaline-torch/src/system.cpp
Thanks to @PicoCentauri and @frostedoyster for finding these bugs!
----
📚 Documentation preview 📚: https://rascaline--304.org.readthedocs.build/en/304/
=> Torch system was broken

.github/workflows/coverage.yml, .github/workflows/docs.yml, .github/workflows/python-tests.yml, python/rascaline/tests/utils/splines.py, tox.ini
----
📚 Documentation preview 📚: https://rascaline--309.org.readthedocs.build/en/309/
=> Pin tox version in tox.ini

rascaline-torch/CMakeLists.txt, rascaline-torch/src/autograd.cpp, rascaline-torch/src/openmp.cpp, rascaline-torch/src/openmp.hpp, rascaline-torch/tests/calculator.cpp
This is working on my machine, now to debug the build on other platforms!
----
📚 Documentation preview 📚: https://rascaline--307.org.readthedocs.build/en/307/
=> Use OpenMP to parallelize Autograd::backward in rascaline-torch

python/Cargo.toml, rascaline-c-api/Cargo.toml, rascaline-torch/Cargo.toml, rascaline/src/calculators/soap/radial_integral/gto.rs, rascaline/src/math/exp.rs
----
📚 Documentation preview 📚: https://rascaline--322.org.readthedocs.build/en/322/
=> Fix new lints in rustc 1.80

python/rascaline/rascaline/utils/clebsch_gordan/_cg_product.py, python/rascaline/rascaline/utils/clebsch_gordan/_utils.py
This is a follow-up to #316 
----
📚 Documentation preview 📚: https://rascaline--327.org.readthedocs.build/en/327/
=> Use Labels.select for key selection in ClebschGordanProduct

.github/workflows/rust-tests.yml, CONTRIBUTING.rst, docs/rascaline-json-schema/Cargo.toml, python/Cargo.toml, rascaline-c-api/Cargo.toml, rascaline-c-api/build.rs, rascaline-c-api/include/rascaline.h, rascaline-torch/Cargo.toml, rascaline/Cargo.toml, rascaline/benches/lode-spherical-expansion.rs, rascaline/benches/soap-power-spectrum.rs, rascaline/benches/soap-radial-integral.rs, rascaline/benches/soap-spherical-expansion.rs, rascaline/benches/spherical-harmonics.rs, rascaline/src/calculators/lode/spherical_expansion.rs, rascaline/src/calculators/soap/radial_spectrum.rs
Follow up to https://github.com/metatensor/metatensor/pull/736
----
📚 Documentation preview 📚: https://rascaline--331.org.readthedocs.build/en/331/
=> Require rustc v1.74 to build the code

python/rascaline/rascaline/utils/clebsch_gordan/_coefficients.py
----
📚 Documentation preview 📚: https://rascaline--333.org.readthedocs.build/en/333/
=> Remove needless transpose in complex to real CG conversion

rascaline/src/calculator.rs, rascaline/src/calculators/soap/power_spectrum.rs, rascaline/src/calculators/soap/radial_spectrum.rs, rascaline/src/calculators/soap/spherical_expansion.rs, rascaline/src/calculators/soap/spherical_expansion_pair.rs, rascaline/src/tutorials/moments/moments.rs, rascaline/src/tutorials/moments/s3_compute_5.rs
----
📚 Documentation preview 📚: https://rascaline--334.org.readthedocs.build/en/334/
=> Handle the case where selections create an empty TensorMap

pyproject.toml, python/rascaline/rascaline/systems/base.py, python/rascaline/rascaline/utils/_backend.py, python/rascaline/rascaline/utils/clebsch_gordan/_coefficients.py, python/rascaline/rascaline/utils/clebsch_gordan/_density_correlations.py, python/rascaline/rascaline/utils/clebsch_gordan/_utils.py, python/rascaline/rascaline/utils/splines/splines.py, python/rascaline/tests/utils/utils.py, tox.ini
----
📚 Documentation preview 📚: https://rascaline--342.org.readthedocs.build/en/342/
=> Switch to ruff for linting & formatting

.codecov.yml, .github/workflows/coverage.yml, .github/workflows/docs.yml, .github/workflows/rust-tests.yml, .github/workflows/torch-tests.yml
----
📚 Documentation preview 📚: https://featomic--346.org.readthedocs.build/en/346/
=> Upgrade Github Action versions

featomic-torch/CMakeLists.txt, featomic-torch/cmake/dev-versions.cmake, featomic/CMakeLists.txt, featomic/Cargo.toml, featomic/cmake/dev-versions.cmake, featomic/tests/cmake-project/CMakeLists.txt
----
📚 Documentation preview 📚: https://featomic--355.org.readthedocs.build/en/355/
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/metatensor/featomic/actions/artifacts/2286119104.zip)
=> Release featomic v0.6.0 rc1

.github/workflows/build-wheels.yml, featomic-torch/CMakeLists.txt, featomic/Cargo.toml, featomic/tests/cmake-project/CMakeLists.txt
----
📚 Documentation preview 📚: https://featomic--356.org.readthedocs.build/en/356/
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/metatensor/featomic/actions/artifacts/2294318254.zip)
=> Release featomic 0.6.0 rc2

python/featomic/featomic/clebsch_gordan/_density_correlations.py
----
📚 Documentation preview 📚: https://featomic--358.org.readthedocs.build/en/358/
=> Update _density_correlations.py module docstring

.github/workflows/build-wheels.yml
----
📚 Documentation preview 📚: https://featomic--357.org.readthedocs.build/en/357/
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/metatensor/featomic/actions/artifacts/2295211577.zip)
=> Make sure to include the sdist in the releases

python/featomic_torch/featomic/torch/system.py
----
📚 Documentation preview 📚: https://featomic--362.org.readthedocs.build/en/362/
=> Remove runtime depdendency on packaging for featomic-torch

featomic-torch/CMakeLists.txt, featomic/CHANGELOG.md, featomic/Cargo.toml, featomic/tests/cmake-project/CMakeLists.txt, python/featomic/setup.py
----
📚 Documentation preview 📚: https://featomic--365.org.readthedocs.build/en/365/
=> Release featomic v0.6.0

featomic/Cargo.toml
----
📚 Documentation preview 📚: https://featomic--366.org.readthedocs.build/en/366/
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/metatensor/featomic/actions/artifacts/2390916389.zip)
=> Update Cargo metadata for featomic crate

docs/requirements.txt, featomic-torch/CMakeLists.txt, python/featomic_torch/build-backend/backend.py, python/featomic_torch/setup.py, tox.ini
[📚 Download documentation for this pull-request](https://nightly.link/metatensor/featomic/actions/artifacts/2603661173.zip)
[⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/metatensor/featomic/actions/artifacts/2604176327.zip)
=> Allow using metatensor-torch 0.7.0

featomic-torch/CMakeLists.txt
[📚 Download documentation for this pull-request](https://nightly.link/metatensor/featomic/actions/artifacts/2604878332.zip)
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/metatensor/featomic/actions/artifacts/2604947716.zip)
[📚 Download documentation for this pull-request](https://nightly.link/metatensor/featomic/actions/artifacts/2608715313.zip)
[⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/metatensor/featomic/actions/artifacts/2608788094.zip)
=> Use metetansor torch v0.7.2

CONTRIBUTING.rst, docs/src/explanations/concepts.rst, docs/src/get-started/featomic.rst, docs/src/get-started/installation.rst, featomic-torch/CMakeLists.txt, featomic/CMakeLists.txt, python/featomic/examples/first-calculation.py
[📚 Download documentation for this pull-request](https://nightly.link/metatensor/featomic/actions/artifacts/2629454327.zip)
[⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/metatensor/featomic/actions/artifacts/2629586187.zip)
=> Remove leftover lab-cosmo branding

python/featomic/examples/first-calculation.py
It was still using very old concepts from metatensor
=> Update first-calculation tutorial
